import Head from 'next/head'
import '../styles/globals.css'
import Navbar from '../components/Navbar/index'

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Wiz Sullivan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <Component {...pageProps} />
    </div>
  )
}

export default MyApp
